spring:
  application:
    name: race
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/race_db}
    username: ${DATABASE_USER:race}
    password: ${DATABASE_PASSWORD:race}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  web:
    error:
      include-message: always

  flyway:
    enabled: true
